-- Migration: incluir 'Notificación de ITM' en el bloque DICTAMEN MEDICO del reporte WA.
-- Aplicada: 2026-04-30 sobre wdgdbbcwcrirpnfdmykh.
--
-- Cambios sobre fn_armar_reporte_agendar_srt:
--   1. Header del bloque: "DICTAMEN MÉDICO / ITM — plazo 3 hábiles p/ impugnar".
--   2. Label por línea: CASE WHEN tipo_comunicacion = 'Notificación de ITM'
--      THEN 'ITM' ELSE 'DICT MED' END.
--   3. Filtro WHERE del bloque dictamen ahora usa
--      `tipo_comunicacion IN ('Notificación de Dictamen Médico', 'Notificación de ITM')`.
--   4. Post-check de huérfanos también incluye 'Notificación de ITM'.
--
-- El SQL aplicado fue un CREATE OR REPLACE FUNCTION completo (no se versiona
-- aquí porque la fuente de verdad es el cuerpo de la función en Supabase —
-- recuperable con `pg_get_functiondef`).
